[package]
name = "cfl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7.0"
ndarray = {version = "0.15.6", features = ["rayon","approx"] }
ndarray-stats = "0.5.1"
num-complex = "0.4.6"
regex = "1.10.3"
nifti = { version = "0.16.0", optional = true }

[dependencies.ndarray-linalg]
version = "0.16"
optional = true
default-features = false
features = []

[dev-dependencies]
num-traits = "0.2.19"
rand = "0.8.5"

[profile.test]
opt-level = 3

[features]
# By default, no features are enabled: no linalg, minimal dependencies.
default = []

# adds ability to write cfl as a nifti for easy viewing
nifti-dump = [
    "nifti"
]

# Each of these features turns on ndarray-linalg plus a specific backend.
linalg-openblas = [
    "ndarray-linalg",
    "ndarray-linalg/openblas-system"
]

linalg-openblas-static = [
    "ndarray-linalg",
    "ndarray-linalg/openblas-static"
]

linalg-netlib = [
    "ndarray-linalg",
    "ndarray-linalg/netlib-system"
]

linalg-mkl = [
    "ndarray-linalg",
    "ndarray-linalg/intel-mkl-system"
]

linalg-mkl-static = [
    "ndarray-linalg",
    "ndarray-linalg/intel-mkl-static"
]
nifti = ["dep:nifti"]
